### ISSUE TITLE
Concern that testing setup could be affecting production environment

### ISSUE THREAD

**Issue by CodeOfficer** [akauppi/firebase-jest-testing#27]
While integrating **firebase-jest-testing** into my project I ran into these 2 console warnings:

- functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, database, hosting, pubsub, storage

We have cloud functions that make calls to auth() and it would be really bad if our testing env were affecting production. My first thought was to remove `--only firestore,functions` from the run script and just to make sure all emulators were running, but I am unsure if this is the correct way to handle this warning. It seems like I would have to no? 

This warning message does not occur when I run test for the sample app in this repo, but I do see a similar console warning in the [ci/README.md](https://github.com/akauppi/firebase-jest-testing/tree/master/ci) of this repo under "- Build output".

- functions: Unable to fetch project Admin SDK configuration, Admin SDK behavior in Cloud Functions emulator may be incorrect.

In my prior test strategy, I've run firestore integration tests against the emulator but manually passed in credentials to admin.initializeApp() for a completely separate fake firebase`<my project>-testing` app I made just for testing. Even though I was running the emulators locally I wanted to make sure there was no chance of hitting prod on accident. Admittedly I know just enough to be dangerous in this regard and I'm probably doing something unconventional. But it would be nice to be able to pass my own credentials to intializeApp until I can figure out a better way. 

This warning message does occur when I run test for the sample app in this repo.

![image](https://user-images.githubusercontent.com/3593/123328526-ac798880-d509-11eb-88c1-8ebdbecd0d81.png)

**Comment by akauppi** [comment]
There are two different things (warnings) here - let's handle them separately.

---

Thanks for chiming in. This kind of problem is due to the repo having been used only by my naive sample project, which doesn't use Firebase Auth from Functions.

I want to fix this - and have some ideas.

The obvious thing would be to enable Auth emulation. There's no other reason it's not in the group, except for that I didn't need it (I do use it elsewhere). There is no "cost" for it - authentication support is not a downloadable extra but built-in in the Emulators.

But before doing that / alongside it, I'd like to learn more about the use case (we can do that separately, 1-on-1). What kind of authentication integration do your Cloud Functions do?

Is emulating Auth enough, or are they in touch with some cloud services, outside of Firebase?

In those cases, I would prefer doing Jest mocks, instead of having such a test setup running, in the cloud. This is a bit philosophical, but in *many* (all?) cases I've seen people use a "dev" deployment, it's simply because they replicated what they had seen others do... There is a friction involved in running such, and personally I've gone to staging + production (but there can be multiple of both!) thinking.

( You'd need to read my brain to know what I really think, and it's in flux... but .... let's say I'm questioning the need for a "dev" (or "test") deployment, when one has full emulation. And I'd like this repo to lean in the same direction. :) )

---

I've interpreted the nature of the `--only` flag differently.

With my naive sample app, the Cloud Functions are not involved with Auth. I used `--only` to limit the number of emulators to those that the development/testing would need. Maybe just thinking it's faster with fewer, right? 

It has felt wrong that Firebase would "leak" (in my thinking) things to the cloud. I'd keep emulation and "production" (anything cloud) perfectly separate. This obviously eliminates the need for the warnings that raised this issue.

---

When using this repo in my own [app project](http://github.com/akauppi/GroundLevel-firebase-es), I'm using emulators in following ways:

- back-end to help development; run within Docker
- local test runs; emulators run within Docker
- CI tests (no active project)
- CI deployment (has active project)

I feel Firebase CLI could show the warnings only if there is an active Firebase project (`npx firebase-tools use`). If there is not, I don't see the point of them.

My own itch is that I want these warnings gone from the CI *testing* logs.

**Comment by akauppi** [comment]
I'll try to find information on what causes the second 

>Unable to fetch project Admin SDK configuration, Admin SDK behavior in Cloud Functions emulator may be incorrect.

..warning. I have seen it, but don't really understand it.

**Comment by akauppi** [comment]
You can remove the `--only firestore,functions` flag from `package.json`. Without it, the set of emulators are taken from `firebase.json`. But this doesn't really change the reason d'être of this issue, in any way...****

**Comment by akauppi** [comment]
I think my stake on this is to make the lib so safe that the warnings lose their mojo. That things they warn against won't be possible, in reality.

**Comment by CodeOfficer** [comment]
Feels like being able to pass credentials to admin.initializeApp() would be a surefire way to make sure tests are not run on prod.

**Comment by akauppi** [comment]
To clarify this, the title should be read as:

>Concern that **Cloud Functions in** the testing setup could be affecting production environment

That's what we are trying to fix, right?

**Comment by akauppi** [comment]
Current plan for this in `next`. All the changes are on the test project's (not lib's) side.

- running `npm test` or `npm run start` checks that there's no active project.

   If there is, tests are not executed. 

- if that passes, the questionable lines are filtered away from the output, but a warning about this still exists:

```
$ npm run start

> prestart
> npm run -s _checkNoActive


> start
> firebase emulators:start --project=fns-test | $(filter-emulators)

(( Some Firebase Emulator warnings SUPPRESSED. ))
i  emulators: Starting emulators: functions, firestore
⚠  Your requested "node" version "14 || ^16" doesn't match your global version "16"
i  firestore: Firestore Emulator logging to firestore-debug.log
⚠  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/asko/Git/firebase-jest-testing/sample/functions" for Cloud Functions...
✔  functions[mars-central2-greet]: http function initialized (http://localhost:5002/fns-test/mars-central2/greet).
✔  functions[mars-central2-userInfoShadow]: firestore function initialized.
```

I am relatively at ease with this, but would really like to hear how Firebase authors see the situation (and to have the warnings removed, at the source).

---

Then about the providing of credentials to the Cloud Functions. 

That's an issue directly involving the `functions/*.js` and I don't see how `firebase-jest-testing` is involved.

There are two `admin.initializeApp`s in play:

- one within this library (`firestoreAdmin`)
- one in the sources of the Cloud Functions definitions (`sample/functions/index.js`)

>As it happens, one of them is now an "alpha" and the other one is stable - they are completely separate.

The first one only handles Firestore issues, and Firestore is emulated. No problems there?

The second is provided by the user of `firebase-jest-testing`. It can be initialized in any way, but for sanity, it makes sense that:

- it's not given any credentials that provide access to production instances

Found this blog post. https://medium.com/google-cloud/firebase-separating-configuration-from-code-in-admin-sdk-d2bcd2e87de6

@CodeOfficer Does this answer your concerns?

**Comment by akauppi** [comment]
Firebase documents what constitutes a fake and what a real project [here](https://firebase.google.cn/docs/emulator-suite/connect_functions?hl=en&%3Bauthuser=3&authuser=3#choose_a_firebase_project) (Firebase Emulator Suite docs)

Real:

>A real project is one you configured and activated in the Firebase console...

Fake:

>A demo project has no Firebase console configuration and no live resources. Demo project IDs have the demo- prefix.

**Comment by akauppi** [comment]
#29 provides a solution that I think is enough to cover this issue.

In short: use `demo-1` (or similar) as the project id. That makes sure on the Firebase Emulators side that the project is treated "offline".

The other issues will be handled separately.
